### ISSUE TITLE
 license 

### ISSUE THREAD

**Issue by no-1ne** [unmusic/unmusic.github.io#1]
Hey Siva,
Can you clarify the license of the repo specifically the audio files. TIA

**Comment by unmusic** [comment]
@no-1ne Source code is completely free for any use. But the assets like image and audio files have to be replaced with your own files. And host it on your servers. 

I have added the [LICENSE](https://github.com/unmusic/unmusic.github.io/blob/master/LICENSE) file for any future comers.
